version: "1"
services: #Khởi tạo service
    mysql:
        image: mysql:8.0.29-oracle
        ports:
            - "3308:3306" 
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: weather
            MYSQL_USER: thang
            MYSQL_PASSWORD: Thang1610@
            MYSQL_ROOT_PASSWORD: Thang1610@

    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin:latest
    #     ports:
    #         - "8081:80"
    #     depends_on:
    #         - mysql
    #     environment:
    #         PMA_HOSTS: mysql
    #         PMA_PORT: 3306
    #         PMA_USER: thang
    #         PMA_PASSWORD: Thang1610@

    redis:
        image: redis:7.2-alpine
        ports:
            - "6379:6379"
        command: redis-server
        volumes:
            - ./data/redis:/data

    nginx:
        image: "nginx:stable"
        ports:
            - "8000:80"
            - "443:443"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
    
    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        environment:
            - APP_NAME=Laravel
            - APP_ENV=local
            - APP_KEY=base64:mtpMOefOGwji0sWbWONS6qUFtX0JGm80kbahC5PKTYs=
            - APP_DEBUG=true
            - APP_URL=http://localhost
            - LOG_CHANNEL=stack
            - LOG_DEPRECATIONS_CHANNEL=null
            - LOG_LEVEL=debug
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=weather
            - DB_USERNAME=thang
            - DB_PASSWORD=Thang1610@
            - BROADCAST_DRIVER=redis
            - CACHE_DRIVER=redis
            - FILESYSTEM_DISK=local
            - QUEUE_CONNECTION=redis
            - SESSION_DRIVER=redis
            - SESSION_LIFETIME=120
            - MEMCACHED_HOST=127.0.0.1
            - REDIS_HOST=redis
            - REDIS_PASSWORD=null
            - REDIS_PORT=6379
            - MAIL_MAILER=smtp
            - MAIL_HOST=smtp.gmail.com
            - MAIL_PORT=587
            - MAIL_USERNAME=nguyenhuuthangc7@gmail.com
            - MAIL_PASSWORD=vxqvwefsdmclymwi
            - MAIL_ENCRYPTION=null
            - MAIL_FROM_ADDRESS="hello@example.com"
            - MAIL_FROM_NAME="${APP_NAME}"
            - API_KEY_WEATHER="7858617aaeca470ab0085037240304"
        ports:
            - "7000:9000"
